version: '3'

services:
  postgres:
    image: debezium/postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ""
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DATA: "/var/lib/postgresql/data postgres"
  zookeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
